# Generated by Django 5.0.1 on 2024-01-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='stock_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
