# Generated by Django 5.0.1 on 2024-01-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffees', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
