# Generated by Django 5.0.1 on 2024-01-30 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffees', '0006_internaldata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=300, unique=True)),
                ('after_tax_amount', models.IntegerField()),
                ('house_number', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=200)),
                ('distrit', models.CharField(max_length=100)),
                ('other_addresses', models.CharField(max_length=200)),
                ('instructins', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('DLV', 'Delivered'), ('PND', 'Pending'), ('OTW', 'On The Way'), ('XXD', 'Cancelled')], max_length=200)),
                ('coffees', models.ManyToManyField(to='coffees.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
