# Generated by Django 5.0.1 on 2024-01-30 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffees', '0008_orders_created_at_orders_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='distrit',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='instructins',
            new_name='instructions',
        ),
    ]
