# Generated by Django 5.0.1 on 2024-01-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffees', '0009_rename_distrit_orders_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_total',
            field=models.IntegerField(null=True),
        ),
    ]
