# Generated by Django 5.0.1 on 2024-01-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffees', '0010_orders_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total_items',
            field=models.IntegerField(null=True),
        ),
    ]
