# Generated by Django 5.0.1 on 2024-01-30 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffees', '0011_orders_total_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_total',
        ),
    ]
