# Generated by Django 5.0.1 on 2024-01-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffees', '0012_remove_orders_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='coffees',
        ),
        migrations.AddField(
            model_name='orders',
            name='coffees',
            field=models.JSONField(null=True),
        ),
    ]
