# Generated by Django 5.0.1 on 2024-01-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffees', '0013_remove_orders_coffees_orders_coffees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='after_tax_amount',
            field=models.FloatField(),
        ),
    ]
