# Generated by Django 5.0.1 on 2024-01-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffees', '0015_alter_cart_quantity_alter_cart_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
