# Generated by Django 5.0.1 on 2024-02-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffees', '0016_alter_cart_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='discount_percentage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
